my:
  greeting: Hello there
  list:
    values: one,two,three
dbValues: connectionString

db:
  connection: connectionString
  host: 127.0.0.1
  port: 3600

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring.cloud.config.uri: http://localhost:8888
spring:
  config:
    import: "optional:configserver:"
  application:
    name: spring-boot-config